version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ollama:/home/vscode/.ollama
    command: sleep infinity
    environment:
      OLLAMA_HOST: ollama:11434

  ollama:
    image: ollama/ollama
    volumes:
      - $HOME/.ollama:/root/.ollama
